### ISSUE TITLE
Падает приложение, если во время использования выйти из проекта в AndroidStudio

### ISSUE THREAD

**Issue by MaxFix** [DaniilSmirnov/APKInstaller#4]
Шаги:
1 Открыта AndroidStudio с проектом
2 Закрываем проект в AS
ФР -> Приложение падает

`2021-04-19 12:59:00.552 Python[1708:73516] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ppadb/connection.py", line 36, in connect
    self.socket.connect((self.host, self.port))
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ma.spiridonov/Downloads/APKInstaller-master/main.py", line 266, in isActualOnline
    device.get_serial_no()
  File "/usr/local/lib/python3.9/site-packages/ppadb/command/serial/__init__.py", line 65, in get_serial_no
    return self._execute_cmd(cmd)
  File "/usr/local/lib/python3.9/site-packages/ppadb/command/serial/__init__.py", line 6, in _execute_cmd
    conn = self.create_connection(set_transport=False)
  File "/usr/local/lib/python3.9/site-packages/ppadb/device.py", line 42, in create_connection
    conn = self.client.create_connection(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/ppadb/client.py", line 14, in create_connection
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/ppadb/connection.py", line 39, in connect
    raise RuntimeError("ERROR: connecting to {}:{} {}.\nIs adb running on your computer?".format(
RuntimeError: ERROR: connecting to 127.0.0.1:5037 [Errno 61] Connection refused.
Is adb running on your computer?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ppadb/connection.py", line 36, in connect
    self.socket.connect((self.host, self.port))
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ma.spiridonov/Downloads/APKInstaller-master/main.py", line 283, in checkDevicesActuality
    if isActualOnline():
  File "/Users/ma.spiridonov/Downloads/APKInstaller-master/main.py", line 268, in isActualOnline
    ui.drawDevices()
  File "/Users/ma.spiridonov/Downloads/APKInstaller-master/main.py", line 215, in drawDevices
    connected_devices = self.client.devices()
  File "/usr/local/lib/python3.9/site-packages/ppadb/command/host/__init__.py", line 23, in devices
    result = self._execute_cmd(cmd)
  File "/usr/local/lib/python3.9/site-packages/ppadb/command/host/__init__.py", line 13, in _execute_cmd
    with self.create_connection() as conn:
  File "/usr/local/lib/python3.9/site-packages/ppadb/client.py", line 14, in create_connection
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/ppadb/connection.py", line 39, in connect
    raise RuntimeError("ERROR: connecting to {}:{} {}.\nIs adb running on your computer?".format(
RuntimeError: ERROR: connecting to 127.0.0.1:5037 [Errno 61] Connection refused.
Is adb running on your computer?
launch.sh: line 1:  1708 Abort trap: 6           python3 main.py`

**Comment by DaniilSmirnov** [comment]
Закинул в dev ветку фикс на то место, что в логах, если упадет еще раз и в логах будет другая строка, то надо будет этот фикс во все места затолкать

**Comment by DaniilSmirnov** [comment]
Должно стать ок, если не станет, зови)

**Comment by MaxFix** [comment]
Упало )

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ppadb/connection.py", line 36, in connect
    self.socket.connect((self.host, self.port))
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ma.spiridonov/Downloads/APKInstaller-master/main.py", line 260, in checkDevicesActuality
    connected_devices = getDevices()
  File "/Users/ma.spiridonov/Downloads/APKInstaller-master/utils.py", line 18, in getDevices
    return client.devices()
  File "/usr/local/lib/python3.9/site-packages/ppadb/command/host/__init__.py", line 23, in devices
    result = self._execute_cmd(cmd)
  File "/usr/local/lib/python3.9/site-packages/ppadb/command/host/__init__.py", line 13, in _execute_cmd
    with self.create_connection() as conn:
  File "/usr/local/lib/python3.9/site-packages/ppadb/client.py", line 14, in create_connection
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/ppadb/connection.py", line 39, in connect
    raise RuntimeError("ERROR: connecting to {}:{} {}.\nIs adb running on your computer?".format(
RuntimeError: ERROR: connecting to 127.0.0.1:5037 [Errno 61] Connection refused.
Is adb running on your computer?
launch.sh: line 1:  3524 Abort trap: 6           python3 main.py
`

**Comment by MaxFix** [comment]
дев тоже упал
`APKInstaller-dev % sh launch.sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ppadb/connection.py", line 36, in connect
    self.socket.connect((self.host, self.port))
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ma.spiridonov/Downloads/APKInstaller-dev/main.py", line 260, in checkDevicesActuality
    connected_devices = getDevices()
  File "/Users/ma.spiridonov/Downloads/APKInstaller-dev/utils.py", line 18, in getDevices
    return client.devices()
  File "/usr/local/lib/python3.9/site-packages/ppadb/command/host/__init__.py", line 23, in devices
    result = self._execute_cmd(cmd)
  File "/usr/local/lib/python3.9/site-packages/ppadb/command/host/__init__.py", line 13, in _execute_cmd
    with self.create_connection() as conn:
  File "/usr/local/lib/python3.9/site-packages/ppadb/client.py", line 14, in create_connection
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/ppadb/connection.py", line 39, in connect
    raise RuntimeError("ERROR: connecting to {}:{} {}.\nIs adb running on your computer?".format(
RuntimeError: ERROR: connecting to 127.0.0.1:5037 [Errno 61] Connection refused.
Is adb running on your computer?
launch.sh: line 1:  3575 Abort trap: 6           python3 main.py`

[apk_launcher_crash_trace.log](https://github.com/DaniilSmirnov/APKInstaller/files/6339111/apk_launcher_crash_trace.log)
